### PR TITLE
Updates README

### PR DESCRIPTION
**Pull request by sum01**
Reason for moving doxygen was so that you don't have to change the README each time you bump doxgen version, since it was nested in a version folder.

Hopefully the README is more readable, as I tried to nest things nicely under headings & subheadings where the content was related. The only thing I was wondering is if a table of content would be desired, as the README is a tad large.

### CODE REVIEW

**Comment by sago007** [comment]
Thank you. The changes to the README file looks good.
Regarding Doxygen.
I would prefer perhaps having the page pointing to a "latest" Doxygen folder but having releases point to a specific version. It would make no sense to check the link from the 3.1 README and find the 4.0.0 link.

**Comment by sum01** [comment]
Perhaps this http://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdmainpage could be used to create a page with links to all versions?

Or if the `doxygen` folder was just links to all the version folders, then the README wouldn't need constant changing. The user could go to whatever version they're using.

I've never used doxygen though, so not really sure about how extensible the webpages are.

---

Maybe something as crappy as this would be fine?
```html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<title>PlatformFolders Docs</title>
</head>

<body>
	<p>Below is a list of all available <a href="https://www.stack.nl/~dimitri/doxygen/">Doxygen</a> documentation</p>
	<ul>
		<li>
			<a href="v3.0/index.html">v3.0 (Latest)</a>
		</li>
	</ul>
</body>

</html>
```

**Comment by sum01** [comment]
I saw you changed the doxygen url, so I fixed that in the readme & rebased on the changes. Now it's just a README cleanup commit.

**Comment by sum01** [comment]
Any reason why this can't be merged yet? Just curious if there's something I should do.

**Comment by sago007** [comment]
There are no reason. I simply missed the notification.

**Pull request merged**
