### PR TITLE
C++11 & more

### PR DESCRIPTION
**Pull request by sum01**
If you want I can try and split this into a few PR's. I got a bit out-of-scope with the branch.

Anyways, this PR does a few things:

* **Requires C++11**
* Changes `NULL` to C++11 `nullptr`
* Simplifies some ifdefs
* **Creates unit tests for all public functions/methods**
* Pretties up the README
* Uses the C++11 std method of converting UTF16 to UTF8
* Adds a `.astylerc` so contributors can correctly format code to your preferences
* **Fixes Cmake's `find_package()` not finding the lib when searching from external projects**

---

The `find_package` fix was tested on Win10 and Linux. Both worked without having to provide a `-Dplatform_folders_DIR` arg in the cmake call.

### CODE REVIEW

**Comment by sago007** [comment]
Overall it is very positive. Especially the unit tests. I hope that it will be possible to run Linux tests with some environments at some point.

It is a very large number of changes and there are a few things I need to comment on:
I do not like to introduce std::wstring_convert. It is deprecated in C++17, so I assume it is considered a mistake. While using a Windows specific function is usually undesirable, I don't consider it bad then it is specifically used for Windows specific functionality.
The added use of std::string seems a bit too aggressive. throwOnRelative have little to gain and a lot to loose from std::string. At least as long as snprintf is used.

**Comment by sum01** [comment]
I guess I could drop those two commits if you want.

**Comment by sago007** [comment]
I would like that. All other commits looks good to me.

**Comment by sum01** [comment]
All done

**Comment by sago007** [comment]
I checked it out and tested it. Two things:
PUBLIC cxx_std_11 requires CMake 3.8 or newer. Removing the line "PUBLIC cxx_std_11" made it work. I have only tested it on an Ubuntu 16.04. I do expect it to work on a Ubuntu 14.04 too.

The sample program is no longer provided. It annoys me a bit. There are currently no compilable sample program or a way for me to verify that it works.

**Comment by sum01** [comment]
Hmm, good catch, I had no idea `cxx_std_11` was that new. What target Cmake version is your accepted minimum? For an example, Ubuntu 18 LTS has v3.10.2, and 16 LTS has v3.5.1.

I could create an "examples" folder and make a small program or two that maybe read/write to the dirs. That old file is now in `test/integration.cpp`, although changed to use `eval_test()`

**Comment by sago007** [comment]
i would not mind an example folder but I would prefer that the sample program must be compilable without installing the library.

For CMake I would prefer that the oldest Ubuntu LTS was supported. Ubuntu 14.04 comes with 3.5.1.

**Comment by sum01** [comment]
Ok so I reverted the deletion of the example file. Maybe I'll add examples in the future when I get around to it.

Also fixed it to work with an older Cmake. I tested changes on Ubuntu 14 with Cmake v3.5.1 (the `cmake3` package), but I see no reason why it wouldn't work on as early as Cmake v3.1.

**Pull request merged**
